### ISSUE TITLE
Update nightly HoneyBadger configs

### ISSUE THREAD

**Issue by dimakis** [red-hat-data-services/distributed-workloads#17]

**Comment by pablofelix** [comment]
HB MR for ODH nightlies opened, waiting to be reviewed and merged by HB team

**Comment by dimakis** [comment]
Thanks @pablofelix for [this commit](https://gitlab.cee.redhat.com/cpaas-products/rhods/-/commit/96aa8d51881b76343f7631af4e236e18ee46a603)
I can close this now, correct?

**Comment by pablofelix** [comment]
Yes, please close it

**Comment by dimakis** [comment]
Closing as complete
