### ISSUE TITLE
Update nightly midstream repos

### ISSUE THREAD

**Issue by dimakis** [red-hat-data-services/distributed-workloads#18]

**Comment by pablofelix** [comment]
PR created, we can merge it once HB MR is merged along with operator changes

**Comment by dimakis** [comment]
And I think this one is also closable because of [this commit](https://gitlab.cee.redhat.com/cpaas-products/rhods/-/commit/96aa8d51881b76343f7631af4e236e18ee46a603)
@pablofelix , correct? 😄

**Comment by pablofelix** [comment]
yes, correct :)

**Comment by dimakis** [comment]
muchas gracias amigo 😄 

Closed as work is complete
