### ISSUE TITLE
Update 1.35 Honeybadger midstream repos

### ISSUE THREAD

**Issue by dimakis** [red-hat-data-services/distributed-workloads#20]
Midstream:
- Delete https://gitlab.cee.redhat.com/data-hub/rhods-cpaas-midstream/-/tree/rhods-1.18-rhel-8/distgit/containers/odh-codeflare-operator-bundle

- Add CodeFlare variable to https://gitlab.cee.redhat.com/data-hub/rhods-cpaas-midstream/-/blob/rhods-1.18-rhel-8/distgit/containers/odh-operator-bundle/render_templates#L43 

- Add CodeFlare to https://gitlab.cee.redhat.com/data-hub/rhods-cpaas-midstream/-/blob/rhods-1.18-rhel-8/distgit/containers/odh-operator-bundle/bundle-template/manifests/opendatahub-operator.clusterserviceversion.yaml#L1618

**Comment by VanillaSpoon** [comment]
Merge Request Opened here: https://gitlab.cee.redhat.com/data-hub/rhods-cpaas-midstream/-/merge_requests/1192

**Comment by dimakis** [comment]
1.35 is waiting for RHODS operator to be fix

**Comment by pablofelix** [comment]
yes, for the changes to work in 1.35 we need:
1. HB MR to be reviewed and merged by HB team https://gitlab.cee.redhat.com/pipeline/products/-/merge_requests/2121
2. Changes in RHODS operator
